auctions/urls.py
from django.urls import path
from django.views.generic.base import TemplateView

from . import views

urlpatterns = [
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),

    path("", views.ListingListView.as_view(), name="index"),
    #path("", views.index, name="index"),

    path("listing/<int:listing_id>", views.listing, name="listing"),
    path("bid/<int:listing_id>", views.bid, name="bid"),
    path("my_listings", views.my_listings, name="my-listings"),
    path("my_watchlist", views.my_watchlist, name="my-watchlist"),

    path("create_listing", views.ListingCreateView.as_view(), name="create-listing"),
    #path("create_listing", views.create_listing, name="create-listing"),

    path("categories", views.CategoryListView.as_view(), name="categories"),
    #path("categories", views.categories, name="categories"),

    path("category/<int:category_id>", views.CategoryListingsView.as_view(), name="category"),
    #path("category/<int:category_id>", views.category, name="category"),

    path("create_category", views.CategoryCreateView.as_view(), name="create-category"),
    path("category/delete/<int:pk>", views.CategoryDeleteView.as_view(), name="delete-category"),
    path("category/update/<int:pk>", views.CategoryUpdateView.as_view(), name="update-category"),


    path("comment/<int:listing_id>", views.add_comment, name="add-comment"),

    path("api/counters", views.api_counters, name="api-counters"),
    path("api/toggle", views.api_toggle, name="api-toggle"),
    path("api/watching", views.api_watching, name="api-watching"),
    path("api/comment/<int:listing_id>", views.api_comment, name="api-add-comment"),

]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static  

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.core.validators import MinValueValidator


class User(AbstractUser):
    # hang off a user object for convenience in layout header
    def all_listings(self):
        return Listing.objects.all()

    # hang off a user object for convenience in layout header
    def active_listings(self):
        return Listing.objects.filter(active=True)



class Listing(models.Model):
    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name="my_listings")
    title = models.CharField(max_length=64)
    description = models.TextField(max_length=500)
    image = models.ImageField(upload_to='images/listings', blank=True)
    active = models.BooleanField(default=True)
    starting_bid = models.IntegerField(default=1, validators=[MinValueValidator(1)])
    watchers = models.ManyToManyField(User, blank=True, related_name="watched_listings")
    categories = models.ManyToManyField('Category', blank=True, related_name="listings")

    def __str__(self):
        return f'{self.title}'

    def toggle_watcher(self, user):
        user_is_watching = self.watchers.filter(id=user.id).exists()
        if user_is_watching:
            self.watchers.remove(user)
        else:
            self.watchers.add(user)

    def minimum_bid(self):
        return max(self.starting_bid, 1+self.high_bid_amount())

    def high_bid_amount(self):
        bid = self.bids.all().order_by('-created_at').first()
        if bid:
            return bid.amount
        else:
            return 0

    def watcher_count(self):
        return len(self.watchers.all())
 
            

class Bid(models.Model):
    created_at = models.DateTimeField(auto_now=True)
    bidder = models.ForeignKey(User, on_delete=models.CASCADE, related_name="bids")
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name="bids")
    amount = models.IntegerField()


class Comment(models.Model):
    created_at = models.DateTimeField(auto_now=True)
    commentor = models.ForeignKey(User, on_delete=models.CASCADE, related_name="comments")
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name="comments")
    comment = models.TextField(max_length=500)


class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    image = models.ImageField(upload_to='images/categories', blank=True)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

auctions/forms.py
from xml.etree.ElementTree import Comment
from django import forms
from django.core.exceptions import ValidationError

from .models import Listing, Bid, Comment

class ListingForm(forms.ModelForm):

    class Meta:
        model = Listing
        fields = ('title', 'description', 'starting_bid', 'categories', 'image') 
        labels = {
            'starting_bid': "Starting bid (in USD)",
        }

class BidForm(forms.ModelForm):

    class Meta:
        model = Bid
        fields = ('amount', ) 
        labels = {
            'amount': "Amount of bid (in USD)",
        }

    def set_minimum_bid(self, value):
        self.minimum_bid = value

    def clean_amount(self):
        value = int(self.cleaned_data['amount'])
        if value < self.minimum_bid:
            raise ValidationError(f'Bid is too low; must be at least ${self.minimum_bid}')
        return value
    

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('comment', )

auctions/views.py
import re
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseServerError
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy

from .models import User, Listing, Category, Comment
from .forms import ListingForm, BidForm, CommentForm

def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            next_url = request.POST.get("next", "index")
            return redirect(next_url)
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        next_url = request.GET.get("next", "index")
        return render(request, "auctions/login.html", {"next": next_url })


def logout_view(request):
    logout(request)
    return redirect("index")


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return redirect("index")
    else:
        return render(request, "auctions/register.html")


def index(request):
    return render(request, "auctions/index.html", {
        'listings': Listing.objects.all().filter(active=True).order_by('-created_at'),
        'banner': 'Active Listings'
    })

class ListingListView(ListView):
    model = Listing
    template_name = "auctions/index.html"
    context_object_name = "listings"

    def get_queryset(self):
        return Listing.objects.all().filter(active=True).order_by('-created_at')

    def get_context_data(self):
        context = super().get_context_data()
        context['banner'] = "Active Listings"
        return context


def listing(request, listing_id):
    listing = get_object_or_404(Listing, id=listing_id)
    if request.method == 'POST':
        clicked = request.POST["doit"]
        if clicked == "toggle-watcher":
            listing.toggle_watcher(request.user)
            return redirect('listing', listing_id=listing.id)
        elif clicked == "bid":
            return redirect('bid', listing_id=listing.id)
            return HttpResponse("make a bid")
        elif clicked == "close-auction":
            listing.active = False
            listing.save()
            return redirect('my-listings')
        elif clicked == "add-comment":
            return redirect('add-comment', listing_id=listing_id)
        else:
            return HttpResponseServerError(f'Unknown button clicked')
    else:
        being_watched = listing.watchers.filter(id=request.user.id).exists()
        return render(request, "auctions/listing.html", {
            'listing': listing,
            'being_watched': being_watched,
        })

@login_required(login_url='login')
def my_listings(request):
    return render(request, "auctions/index.html", {
        'listings': request.user.my_listings.order_by('-created_at'),
        'banner': 'My Listings'
    })

@login_required(login_url='login')
def my_watchlist(request):
    return render(request, "auctions/index.html", {
        'listings': request.user.watched_listings.order_by('-created_at'),
        'banner': 'My Watchlist'
    })

def categories(request):
    return render(request, "auctions/categories.html", {
        'categories': Category.objects.all().order_by('name'),
    })

class CategoryListView(ListView):
   model = Category
   template_name = "auctions/categories.html"
   context_object_name = "categories"


def category(request, category_id):
    category = get_object_or_404(Category, id=category_id)
    listings = Listing.objects.filter(categories = category, active=True)
    return render(request, "auctions/index.html", {
        'listings': listings,
        'banner': f'{category.name} Listings',
    })

class CategoryListingsView(ListView):
   model = Listing
   template_name = "auctions/category_listings.html"
   context_object_name = "listings"
 
   def get_queryset(self):
       return Listing.objects.filter(categories=self.kwargs["category_id"], active=True)
 
   def get_context_data(self):
       context = super().get_context_data()
       category_id = self.kwargs["category_id"]
       category = Category.objects.get(id=category_id)
       context['category'] = category
       context['banner'] = f'{category.name} Category ({self.get_queryset().count()} listings)'
       return context

class CategoryCreateView(CreateView):
    model = Category
    fields = ('name', 'image')
    success_url = reverse_lazy('categories')

class CategoryDeleteView(DeleteView):
    model = Category
    success_url = reverse_lazy('categories')

class CategoryUpdateView(UpdateView):
   model = Category
   fields = ("name", "image")
   success_url = reverse_lazy("categories")

@login_required(login_url='login')
def create_listing(request):
    if request.method == "POST":
        if "cancel" in request.POST: 
            return redirect('index')
        form = ListingForm(request.POST, request.FILES)
        if form.is_valid():
            listing = form.save(commit=False)
            listing.creator = request.user
            listing.save()
            form.save_m2m()
            messages.success(request, f'Listing created successfully!')
            return redirect("index")
        else:
            messages.error(request, 'Problem creating the listing. Details below.')	
    else: 
        form = ListingForm(initial={'starting_bid': 1})
    return render(request, "auctions/new_listing.html", {'form':form})

#class ListingCreateView(LoginRequiredMixin, CreateView):
class ListingCreateView(CreateView):
    model = Listing
    template_name = "auctions/new_listing.html"
    fields = ('title', 'description', 'starting_bid', 'categories', 'image')
    success_url = reverse_lazy('index')

    def form_valid(self, form):
        form.instance.creator = self.request.user
        return super().form_valid(form)

@login_required(login_url='login')
# possible todo: prevent user to bid on his own listing
def bid(request, listing_id):
    listing = get_object_or_404(Listing, id=listing_id)
    if request.method == 'POST':
        form = BidForm(request.POST)
        form.set_minimum_bid(listing.minimum_bid())
        if form.is_valid():
            bid = form.save(commit=False)
            bid.bidder = request.user
            bid.listing = listing
            bid.save()
            return redirect('listing', listing_id=listing_id)
        else:
            messages.error(request, "Problem with the bid")
    else:
        form = BidForm(initial={'amount':listing.minimum_bid})
    return render(request, "auctions/bid.html", {
            'form': form,
            'listing': listing,
        }) 

@login_required(login_url='login')
def add_comment(request, listing_id):
    listing = get_object_or_404(Listing, id=listing_id)
    if request.method == "POST":
        if "cancel" in request.POST: 
            return redirect('listing', listing_id=listing_id)
        form = CommentForm(request.POST, request.FILES)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.commentor = request.user
            comment.listing = listing
            comment.save()
            return redirect('listing', listing_id=listing_id)
        else:
            messages.error(request, 'Problem creating the comment. Details below.')	
    else: 
        form = CommentForm()
    # return render(request, "auctions/listing.html", {
    #     'form':form, 'listing':listing, 'show_CommentForm':'yes'})
    return render(request, "auctions/new_comment.html", {
        'form':form, 'listing':listing, 'show_CommentForm':'yes'})

from django.http import JsonResponse
def api_counters(request):
    user = request.user
    counts = {'active_listings': Listing.objects.filter(active=True).count()}
    if user.is_authenticated:
        counts['my_listings'] = user.my_listings.all().count()
        counts['my_watches'] = user.watched_listings.all().count()
    print(f'api_counters called. returning {counts}')
    return JsonResponse(counts)

def api_toggle(request):
    if not request.user.is_authenticated:
        return JsonResponse({})
    listing_id = request.GET['listing_id']
    listing = Listing.objects.get(id=listing_id)
    on_watchlist = listing.watchers.filter(id=request.user.id).exists()
    if on_watchlist:
        listing.watchers.remove(request.user)
    else:
        listing.watchers.add(request.user)
    on_watchlist = not on_watchlist
    status = {
        'user': request.user.username,
        'on_watchlist': on_watchlist,
        'my_watches': request.user.watched_listings.all().count()
    }
    print(f'api_toggle called. returning {status}')
    return JsonResponse(status)

def api_watching(request):
    # should check of user is_authenticated and listing_id is valid

auctions/templates/auctions/bid.html
{% extends "auctions/layout.html" %}

{% block main %}

{% for m in messages %}
<h2 class="{{m.tags}}">{{m}}</h2>
{% endfor %}

<h2>Bidding on {{ listing.title }}</h2>

<p>Your bid must be at least ${{ listing.minimum_bid }}</p>
<form action="{% url 'bid' listing.id %}" method="POST">
    {% csrf_token %}
    {{ form.as_table }}
    <button type="submit" name="doit" value="bid">Place Bid</button>
</form>
{% endblock %}

auctions/templates/auctions/categories.html
{% extends "auctions/layout.html" %}

{% block main %}

<h2>Categories</h2>

<button onclick="location.href='{% url "create-category" %}'">
    New Category
 </button>
 
<article>
    {% for c in categories %}
        <section>
            <span style="display:inline-block;width:200px;vertical-align:middle;">
            {% if c.image %}
                <img src="{{ c.image.url }}">
            {% endif %}
            </span>
            <a style="font-size:150%;" href="{% url 'category' c.id %}">{{ c.name }}</a>
        </section>
    {% endfor %}
</article>


{% endblock %}

auctions/templates/auctions/category_confirm_delete.html
{% extends "auctions/layout.html" %}
{% block main %}
 
<form method="post">{% csrf_token %}
   <p>Are you sure you want to delete category "{{ object }}"?</p>
   {{ form }}
   <input type="submit" value="Confirm">
</form>
 
{% endblock %}

auctions/templates/auctions/category_form.html
{% extends "auctions/layout.html" %}
{% load static %}
 
{% block main %}

<h3>{{ title }}</h3>
<form method="post" enctype="multipart/form-data">
   {% csrf_token %}
   <table>
       {{ form.as_table }}
   </table>
   <input type="submit" value="Submit">
   <input value="Cancel" type="button" onclick="location.href='{% url "categories" %}'">
</form>

{% endblock %}

auctions/templates/auctions/category_listings.html
{% extends "auctions/layout.html" %}
{% load static %}

{% block main %}
    
<h2>{{banner}}</h2>

<button onclick="location.href='{% url "delete-category" category.id %}'">
    Delete Category
 </button>
 <button onclick="location.href='{% url "update-category" category.id %}'">
    Edit Category
 </button>
 
{% include "auctions/listings_table.html" %}

{% endblock %}

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}
{% load static %}

{% block main %}
    
<h2>{{banner}}</h2>

{% include "auctions/listings_table.html" %}

{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}Auctions{% endblock %}</title>
        <link rel="stylesheet" type="text/css" href="https://cdn.simplecss.org/simple.css">
        <link rel="stylesheet" type="text/css" href="{% static 'auctions/uaa490styles.css' %}" >
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    </head>
    <body>
        <header>
            <h1>Auctions "R" Us</h1>
            <nav>
                <span>
                    <a href="{% url 'index' %}">Active Listings -
                            <span id="al" class="watcher-badge">{{ user.active_listings.count }} </span></a>
                    <a href="{% url 'categories' %}">Categories</a>
                    {% if user.is_authenticated %}
                        <a href="{% url 'my-listings' %}">My Listings - 
                            <span id="ml" class="watcher-badge"> {{ user.my_listings.all.count }} </span></a>
                        <a href="{% url 'my-watchlist' %}">My Watchlist -
                            <span id="mw" class="watcher-badge"> {{ user.watched_listings.all|length }}</span></a>
                        <a href="{% url 'create-listing' %}">Create Listing</a>
                    {% endif %}
                </span>
                <span>
                    {% if user.is_authenticated %}
                        Welcome <strong>{{ user.username }}!</strong>
                        <a href="{% url 'logout' %}">Log Out</a>
                    {% else %}
                        <a href="{% url 'login' %}">Log In</a>
                        <a href="{% url 'register' %}">Register</a>
                    {% endif %}
                </span>
            </nav>
        </header>
        <main>
            {% for m in messages %}
                <h2 class="{{m.tags}}">{{m}}</h2>
            {% endfor %}
    
            {% block main %}
            {% endblock %}
        </main>
        <script src="{% static 'auctions/auctions.js' %}"></script>

     </body>
</html>

auctions/templates/auctions/listing.html
{% extends "auctions/layout.html" %}
{% load static %}

{% block main %}


<h2>
    {% if user.is_authenticated %}
        <img class="toggle_watchlist" data-listing_id="{{listing.id}}" src="{% static 'auctions/hollow-star.png' %}">
        <!-- 
            <span class="toggler material-symbols-outlined">
            star
            </span>
            <span class="filled toggler material-symbols-outlined">
                star
                </span>
                <span class="invis toggler material-symbols-outlined">
                    star
                    </span>
                -->
            {% endif %}
    {{ listing.title }}
    | <small>High bid: ${{ listing.high_bid_amount }}</small>
    {% if not listing.active %}
        - Bidding ended
    {% endif %}
</h2>

<div style="display:flex">
    {% if listing.image %}
        <img src="{{ listing.image.url }}" style="vertical-align:middle;width:100px;margin-right:10px" >
    {% endif %}
    <div style="width:100%""> 
        <div class="listing-description">
            {{ listing.description }}
        </div>
        <div class="listing-categories">
            Categor{{ listing.categories.all|pluralize:"y,ies" }}:
            {% for c in listing.categories.all %}
                <span class="listing-category">{{ c }}</span>{% if not forloop.last %} - {% endif %}
            {% empty %}
                None
            {% endfor %}
        </div>
    </div>
</div>


<p style="font-size:small">Listing by <strong>{{ listing.creator }}</strong> at {{ listing.created_at }}</p>

<form action="{% url 'listing' listing.id %}"method="POST">
    {% csrf_token %}

    <p>
        {% if user.is_authenticated %}
        <button class="listing-button" type="submit" name="doit" value="toggle-watcher">
            {% if being_watched %}
                Stop Watching
            {% else %}
                Add to my watchlist
            {% endif %}
        </button>
        {% endif %}
        {% if listing.watcher_count == 0 %} There are no watchers. You can be the first!
        {% else %} There {{ listing.watcher_count|pluralize:"is,are" }} {{ listing.watcher_count }} watcher{{ listing.watcher_count|pluralize:"s" }}.
        {% endif %}
    </p>
 
    <p>
        {% if not listing.active %}
            Bidding for this item has ended. 
            {% if listing.high_bid %}
                There were {{ listing.bid_count }} bids. Winning bid was for ${{ listing.high_bid.amount}} by {{ listing.high_bid.bidder }}.
            {% else %}
                There were no bids. 
            {% endif %}
        {% else %}
            {% if user.is_authenticated %}
                {% if user == listing.creator %}
                    <button class="listing-button" type="submit" name="doit" value="close-auction">Close Auction</button>
                {% else %}
                    <button class="listing-button" type="submit" name="doit" value="bid">Bid!</button>
                {% endif %}
            {% endif %}
            {% if listing.high_bid %}
                Current high bid is for ${{ listing.high_bid.amount }} by {{ listing.high_bid.bidder }}.
            {% else %}
                There are currently no bids. Minimum bid is ${{ listing.minimum_bid }}.
            {% endif %}
        {% endif %}
    </p>

    <p>
        {% if listing.active %}
            {% if show_CommentForm %} 
                </form>
                {% include 'auctions/new_comment_form.html' %} 
            {% else %}
                <button class="listing-button" type="submit" name="doit" value="add-comment">Add Comment</button>
            {% endif %}
            {% if listing.comment_count == 0 %} Be the first to comment!
            {% else %} {{ listing.comment_count }} comments:
            {% endif %}
        {% else %}
            {% if listing.comment_count == 0 %} There were no comments!
            {% else %} {{ listing.comment_count }} comments:
            {% endif %}
        {% endif %}
    </p>


    <article class="comments">
    {% for c in listing.comments.all reversed%}
        <section class="comments">
            <p>{{ c.comment }}</p>
            <p style="font-size:small">Posted by <strong>{{c.commentor}}</strong> at {{c.created_at}}</p>
        </section>
    {% endfor %}
    </article>
</form>

{% endblock %}

auctions/templates/auctions/listings_table.html
{% load static %}
<!-- included by a template that wants to show listings. assumes context variable {{listings}}
-->
<article class="listings">
    {% for listing in listings %}
        <section class="listings">
            <h4>
                {% if user.is_authenticated %}
                    <img class="toggle_watchlist" data-listing_id="{{listing.id}}" src="{% static 'auctions/hollow-star.png' %}">
                {% endif %}
                {% if listing.image %}
                    <img src="{{ listing.image.url }}" style="vertical-align:middle;width:50px;margin-right:10px" >
                {% endif %}
                <a href="{% url 'listing' listing.id %}"">{{listing.title}}</a>
                | <small>
                    High Bid: ${{ listing.high_bid_amount }}
                    {% if not listing.active %}
                        - Auction Closed
                    {% endif %}
                </small>
            </h4>
            <!--
            <div class="listing-description">{{ listing.description }}</div>
            <p>
                {{listing.watchers.all | length }} watcher{{ listing.watchers.all|pluralize:"s"}}
                | {{listing.bids.all | length }} bidder{{ listing.bids.all|pluralize:"s"}}
                | {{listing.comments.all | length }} comment{{ listing.comments.all|pluralize:"s"}}
            </p>
            -->
        </section>
    {% endfor %}
</article>

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block main %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input type="submit" value="Login">
        <input type="hidden" name="next" value="{{ next }}">
    
    </form>

    <p>
        Don't have an account? <a href="{% url 'register' %}">Register here.</a>
    </p>


{% endblock %}

auctions/templates/auctions/new_comment.html
{% extends "auctions/layout.html" %}

{% block main %}
<script>

function getCookie(name) {
  const value = `; ${document.cookie}`;
  const parts = value.split(`; ${name}=`);
  if (parts.length === 2) return parts.pop().split(';').shift();
}

document.addEventListener('DOMContentLoaded', ()=> {

    document.querySelector('form').onsubmit = ()=> {
        id = document.querySelector('form').id;
        const comment = document.querySelector('#id_comment').value;
        document.querySelector('#id_comment').value = '';
        fetch(`/api/comment/${id}`, {
            method: "POST",
            headers: {
                "X-CSRFToken": getCookie("csrftoken"),
            },
            body: JSON.stringify({
                'comment': comment
            })
        })
        .then(response => response.json())
        .then(data => addComment(data))
        .catch(error => {
            console.log("*** api/comment error **", error);
        })
        return false;
    }
})

function addComment(data) {
    const section = document.createElement('section');
    section.classList.add("comments");

    const p1 = document.createElement('p');
    p1.innerHTML = data["comment"];

    const p2 = document.createElement('p');
    p2.style.fontSize = "small";
    p2.innerHTML = `Posted by <strong>${data["commentor"]}</strong> at ${data["created_at"]}`

    section.append(p1);
    section.append(p2);
    document.querySelector('article').prepend(section);
}

</script>


<h2>Commenting on {{ listing.title }}</h2>


<form id="{{listing.id}}" method="POST">
    {% csrf_token %}
    {{ form.as_table }}
    <div>
        <input type="submit" name="cancel" value="Cancel" formnovalidate="formnovalidate" 
            onClick="window.location = '{% url "listing" listing.id %}'">
        <input type="reset" name="reset" value="Reset">
        <input type="submit" name="submit" value="Add Comment">
    </div>
</form>

<article class="comments">
    {% for c in listing.comments.all reversed %}
        <section class="comments">
            <p>{{ c.comment }}</p>
            <p style="font-size:small">Posted by <strong>{{c.commentor}}</strong> at {{c.created_at}}</p>
        </section>
    {% endfor %}
</article>

{% endblock %}

auctions/templates/auctions/new_comment_form.html
<form action="{% url 'add-comment' listing.id %}" method="POST">
    {% csrf_token %}
    {{ form.as_table }}
    <div>
        <input type="submit" name="cancel" value="Cancel" formnovalidate="formnovalidate">
        <input type="reset" name="reset" value="Reset">
        <input type="submit" name="submit" value="Add Comment">
    </div>
</form>

auctions/templates/auctions/new_listing.html
{% extends "auctions/layout.html" %}

{% block main %}

    <h2>Create Listing</h2>

    {% for m in messages %}
        <h2 class="{{m.tags}}">{{m}}</h2>
    {% endfor %}

    <form action="{% url 'create-listing' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_table }}
        <div>
            <input type="submit" name="cancel" value="Cancel" formnovalidate="formnovalidate">
            <input type="reset" name="reset" value="Reset">
            <input type="submit" name="submit" value="Create Listing">
        </div>
    </form>

{% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block main %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input type="submit" value="Register">
    </form>

    <p>
        Already have an account? <a href="{% url 'login' %}">Log In here.</a>
    </p>

{% endblock %}